# Generated by Django 3.2.3 on 2021-05-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_from', models.CharField(max_length=30)),
                ('city_to', models.CharField(max_length=30)),
                ('departure_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.customer')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab.plane')),
            ],
        ),
    ]
